"""Initial schema with DateTime fields

Revision ID: 82328944302f
Revises: 
Create Date: 2025-12-27 15:06:43.572278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82328944302f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('collection_interval', sa.Integer(), nullable=False),
    sa.Column('preferred_api', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('collection_interval > 0', name='check_collection_interval'),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='check_latitude'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='check_longitude'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_locations_country_code'), 'locations', ['country_code'], unique=False)
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.String(length=255), nullable=False, comment='External alert ID from source API for deduplication'),
    sa.Column('source_api', sa.String(length=50), nullable=False),
    sa.Column('event', sa.String(length=255), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('urgency', sa.String(length=50), nullable=False),
    sa.Column('certainty', sa.String(length=50), nullable=True),
    sa.Column('effective', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=False),
    sa.Column('onset', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends', sa.DateTime(timezone=True), nullable=True),
    sa.Column('areas', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='When this alert was fetched and stored'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_id'), 'alerts', ['alert_id'], unique=False)
    op.create_index('ix_alerts_dedup', 'alerts', ['location_id', 'alert_id', 'source_api'], unique=True)
    op.create_index(op.f('ix_alerts_effective'), 'alerts', ['effective'], unique=False)
    op.create_index(op.f('ix_alerts_event'), 'alerts', ['event'], unique=False)
    op.create_index(op.f('ix_alerts_expires'), 'alerts', ['expires'], unique=False)
    op.create_index('ix_alerts_location_expires', 'alerts', ['location_id', 'expires'], unique=False)
    op.create_index(op.f('ix_alerts_location_id'), 'alerts', ['location_id'], unique=False)
    op.create_table('weather_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_api', sa.String(length=50), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('temperature_fahrenheit', sa.Float(), nullable=True),
    sa.Column('feels_like', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Integer(), nullable=True),
    sa.Column('wind_gust', sa.Float(), nullable=True),
    sa.Column('precipitation', sa.Float(), nullable=True),
    sa.Column('cloud_cover', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.Integer(), nullable=True),
    sa.Column('uv_index', sa.Integer(), nullable=True),
    sa.Column('condition_code', sa.String(length=50), nullable=True),
    sa.Column('condition_text', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sunrise', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sunset', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_weather_data_location_id'), 'weather_data', ['location_id'], unique=False)
    op.create_index(op.f('ix_weather_data_timestamp'), 'weather_data', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_data_timestamp'), table_name='weather_data')
    op.drop_index(op.f('ix_weather_data_location_id'), table_name='weather_data')
    op.drop_table('weather_data')
    op.drop_index(op.f('ix_alerts_location_id'), table_name='alerts')
    op.drop_index('ix_alerts_location_expires', table_name='alerts')
    op.drop_index(op.f('ix_alerts_expires'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_event'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_effective'), table_name='alerts')
    op.drop_index('ix_alerts_dedup', table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_index(op.f('ix_locations_country_code'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
